{
 "title": "Go runtime metrics",
 "description": "Go runtime metrics dashboard from prometheues datasource",
 "tags": [
  "umap",
  "network layer",
  "go",
  "runtime"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "job",
    "query": "label_values(go_goroutines, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "process memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"^($job)$\"}",
     "legendFormat": "resident",
     "query": "process_resident_memory_bytes{job=~\"^($job)$\"}"
    },
    {
     "expr": "process_virtual_memory_bytes{job=~\"^($job)$\"}",
     "legendFormat": "virtual",
     "query": "process_virtual_memory_bytes{job=~\"^($job)$\"}"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=~\"^($job)$\"}[$interval])",
     "legendFormat": "resident",
     "query": "rate(process_resident_memory_bytes{job=~\"^($job)$\"}[$interval])"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{job=~\"^($job)$\"}[$interval])",
     "legendFormat": "virtual",
     "query": "deriv(process_virtual_memory_bytes{job=~\"^($job)$\"}[$interval])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"^($job)\"}",
     "legendFormat": "{{job}} - goroutines",
     "query": "go_goroutines{job=~\"^($job)\"}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"^($job)\"}",
     "legendFormat": "{{job}} - {{ quantile }}",
     "query": "go_gc_duration_seconds{job=~\"^($job)\"}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"^($job)\"}",
     "legendFormat": "{{job}} - - bytes allocated",
     "query": "go_memstats_alloc_bytes{job=~\"^($job)\"}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"^($job)\"}",
     "legendFormat": "{{job}} - stack inuse",
     "query": "go_memstats_stack_inuse_bytes{job=~\"^($job)\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"^($job)\"}",
     "legendFormat": "{{job}} - heap inuse",
     "query": "go_memstats_heap_inuse_bytes{job=~\"^($job)\"}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"^($job)\"}[30s])",
     "legendFormat": "{{job}} - alloc rate",
     "query": "rate(go_memstats_alloc_bytes_total{job=~\"^($job)\"}[30s])"
    }
   ]
  },
  {
   "title": "process open fds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"^($job)\"}",
     "legendFormat": "{{job}} open fds",
     "query": "process_open_fds{job=~\"^($job)\"}"
    }
   ]
  }
 ]
}